"""empty message

Revision ID: 118aaa72b554
Revises: 5597970b6bde
Create Date: 2021-02-16 18:11:54.437533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '118aaa72b554'
down_revision = '5597970b6bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shows', 'description')
    # ### end Alembic commands ###
