"""empty message

Revision ID: 267e8ffa068e
Revises: 189ef5fe2ddd
Create Date: 2021-02-16 17:43:09.981681

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '267e8ffa068e'
down_revision = '189ef5fe2ddd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genres', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    # ### end Alembic commands ###
