"""empty message

Revision ID: 5597970b6bde
Revises: 683e1832ce9c
Create Date: 2021-02-16 18:01:31.935849

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5597970b6bde'
down_revision = '683e1832ce9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('Start_time', sa.DateTime(), nullable=False))
    op.drop_column('shows', 'start_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shows', sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('shows', 'Start_time')
    # ### end Alembic commands ###
