"""empty message

Revision ID: b58312b8f882
Revises: 29f2c6fa4258
Create Date: 2021-02-17 22:36:11.522516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58312b8f882'
down_revision = '29f2c6fa4258'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'Shows', 'Venue', ['Venue_id'], ['id'])
    op.create_foreign_key(None, 'Shows', 'Artist', ['Artist_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    op.drop_constraint(None, 'Shows', type_='foreignkey')
    # ### end Alembic commands ###
